In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.26.4


In [4]:
np.array([1,2,3])

array([1, 2, 3])

In [5]:
np.array([[1,2,3],
         [4,5,6],])

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
ones= np.ones((6,5))

In [7]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
zeros= np.zeros((10,2))

In [9]:
ones.astype(int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
range_array= np.arange(0,10,3)

In [11]:
range_array*3/4*0.9

array([0.   , 2.025, 4.05 , 6.075])

In [12]:
randInt= np.random.randint(5, size=(5,2))

In [13]:
randFloot= np.random.random((5,2))

In [14]:
randInt

array([[1, 0],
       [3, 2],
       [1, 3],
       [3, 4],
       [2, 2]])

In [15]:
randFloot

array([[0.75992771, 0.75738687],
       [0.7496809 , 0.86896563],
       [0.6699763 , 0.15708638],
       [0.16318646, 0.83085788],
       [0.79613251, 0.0253514 ]])

In [16]:
 np.random.random((5,2))

array([[0.08563406, 0.32042413],
       [0.77774347, 0.39464247],
       [0.11542742, 0.82216084],
       [0.16626658, 0.41575618],
       [0.90270261, 0.49262251]])

In [17]:
 np.random.random((5,2))

array([[0.39746924, 0.53656524],
       [0.07514493, 0.12038946],
       [0.62063808, 0.93633012],
       [0.2164431 , 0.99240581],
       [0.6891005 , 0.55767695]])

In [18]:
 np.random.random((5,2))

array([[0.74899231, 0.27076864],
       [0.96567687, 0.10575975],
       [0.78503778, 0.61385502],
       [0.36559809, 0.59077818],
       [0.29948112, 0.32456118]])

In [19]:
 np.random.random((5,2))

array([[0.50539151, 0.89293766],
       [0.9095273 , 0.535312  ],
       [0.97373359, 0.1810562 ],
       [0.30733764, 0.05236093],
       [0.53621788, 0.69671678]])

In [20]:
 np.random.random((5,2))

array([[0.09010636, 0.32601875],
       [0.28774426, 0.12677415],
       [0.66993199, 0.86813512],
       [0.14535401, 0.53096244],
       [0.98957901, 0.47861491]])

In [21]:
 np.random.seed(0)

In [22]:
np.random.randint(10, size=(5,2))

array([[5, 0],
       [3, 3],
       [7, 9],
       [3, 5],
       [2, 4]])

In [23]:
ar=np.random.randint(10, size=(7))

In [24]:
ar

array([7, 6, 8, 8, 1, 6, 7])

In [25]:
ar[0]

7

In [26]:
ar[ :4]

array([7, 6, 8, 8])

In [27]:
arr= np.random.randint(10, size=(3,3))

In [28]:
arr

array([[7, 8, 1],
       [5, 9, 8],
       [9, 4, 3]])

In [29]:
arr[0][2]

1

In [30]:
arr[:2 ,1:]

array([[8, 1],
       [9, 8]])

In [31]:
arrr= np.random.randint(10, size=(3,5,6))

In [32]:
arrr

array([[[0, 3, 5, 0, 2, 3],
        [8, 1, 3, 3, 3, 7],
        [0, 1, 9, 9, 0, 4],
        [7, 3, 2, 7, 2, 0],
        [0, 4, 5, 5, 6, 8]],

       [[4, 1, 4, 9, 8, 1],
        [1, 7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5, 9],
        [4, 4, 6, 4, 4, 3],
        [4, 4, 8, 4, 3, 7]],

       [[5, 5, 0, 1, 5, 9],
        [3, 0, 5, 0, 1, 2],
        [4, 2, 0, 3, 2, 0],
        [7, 5, 9, 0, 2, 7],
        [2, 9, 2, 3, 3, 2]]])

In [33]:
arrr[1][1][1]

7

In [37]:
arrr[1: , 1: , 1:]

array([[[7, 9, 9, 3, 6],
        [2, 0, 3, 5, 9],
        [4, 6, 4, 4, 3],
        [4, 8, 4, 3, 7]],

       [[0, 5, 0, 1, 2],
        [2, 0, 3, 2, 0],
        [5, 9, 0, 2, 7],
        [9, 2, 3, 3, 2]]])

In [40]:
np.unique(ar)

array([1, 6, 7, 8])